import "./globals.css";
import type { Metadata } from "next";
import { Zilla_Slab } from "next/font/google";
import Provider from "./_trpc/Provider";
import WagmiConfigWrapper from "./_components/web3modalbootstrap";
import { ToastContainer, Slide } from "react-toastify";
import "react-loading-skeleton/dist/skeleton.css";
import { SkeletonTheme } from "react-loading-skeleton";

const zilla_slab = Zilla_Slab({
  weight: ["500", "700", "300"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={zilla_slab.className + " " + "bg-[#121212] text-white h-full"}>
        <Provider>
          <WagmiConfigWrapper>
            <SkeletonTheme baseColor="#202020" highlightColor="#444">
              {children}
            </SkeletonTheme>
          </WagmiConfigWrapper>
        </Provider>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss={false}
          draggable
          pauseOnHover={false}
          theme="dark"
          transition={Slide}
          limit={1}
        />
      </body>
    </html>
  );
}
